# Generated by Django 5.0 on 2024-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_xrayimages_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "doctorid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("doctorname", models.CharField(max_length=100)),
                ("hospital", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                ("speciality", models.CharField(max_length=100)),
            ],
        ),
    ]
